spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/babel?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

openai:
  model: gpt-3.5-turbo
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions